### ISSUE TITLE
NAT traversal

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2052]
This GitHub issue tracks the status of NAT traversal capabilities for rust-libp2p. For an overview across libp2p implementations see libp2p/specs#312.

Please comment below to suggest additions or corrections.

Contributions of any form are welcome. Before you start working on something, please comment below to make sure no work is duplicated.

---

### Transport protocols
- [x] TCP + port-reuse
- [x] QUIC
	- https://github.com/libp2p/rust-libp2p/pull/2289
    - libp2p/rust-libp2p#2801
- [x] Websockets (for signaling with browsers)
- [x] WebRTC
    - libp2p/rust-libp2p#1066
    - https://github.com/libp2p/rust-libp2p/pull/2622

### TURN-like protocols

- [x] circuit relay v1
- [x] circuit relay v2
    - libp2p/specs#314
    - libp2p/rust-libp2p#2059

### Signaling protocols

- [x] Direct connection upgrade through relay
    - libp2p/specs#173
    - libp2p/rust-libp2p#2076
    - Blocked on:
        - https://github.com/libp2p/rust-libp2p/issues/1896
        - https://github.com/libp2p/rust-libp2p/issues/2249
        - https://github.com/libp2p/rust-libp2p/issues/2250

### STUN-like protocols

- [ ] STUN
- [x] AutoNAT
    - libp2p/specs#180
    - https://github.com/libp2p/rust-libp2p/pull/2262/

### Other protocols

- [x] multistream-select v1 simultaneous open
     - libp2p/specs#196
     - libp2p/rust-libp2p#2066
- [x] UPnP
     - https://github.com/libp2p/rust-libp2p/issues/3903

### Misc

- [x] Parallel connection attempts to increase hole punch success rate
    - https://github.com/libp2p/rust-libp2p/issues/1896
    - https://github.com/libp2p/rust-libp2p/pull/2248
- [x] Enable dialing a specific fixed set of addresses for a single peer
    - https://github.com/libp2p/rust-libp2p/issues/2249
- [x] Allow specifying the role of a connection in NetworkBehaviourAction::Dial
    - https://github.com/libp2p/rust-libp2p/issues/2250
    - https://github.com/libp2p/rust-libp2p/pull/2363

**Comment by mxinden** [comment]
**Changelog**
- Referenced https://github.com/libp2p/rust-libp2p/pull/2059 as the rust-libp2p circuit relay v2 implementation.

**Comment by mxinden** [comment]
**Changelog**

- Referenced https://github.com/libp2p/rust-libp2p/pull/1672 for AutoNAT implementation (thanks @dvc94ch).

**Comment by mxinden** [comment]
*Changelog*
- Reference https://github.com/libp2p/rust-libp2p/pull/2066 - an multistream-select 1.0 simultaneous open extension implementation.

**Comment by mxinden** [comment]
**Changelog**

- Reference https://github.com/libp2p/rust-libp2p/pull/2076 - a _Direct Connection Upgrade through Relay_ implementation for rust-libp2p.

**Comment by mxinden** [comment]
**Changelog**

- Reference https://github.com/libp2p/rust-libp2p/issues/1896 to increase hole punch success rate.

**Comment by mxinden** [comment]
**Changelog**

- Reference draft pull request https://github.com/libp2p/rust-libp2p/pull/2248 fixing https://github.com/libp2p/rust-libp2p/issues/1896.

**Comment by mxinden** [comment]
**Changelog**

- Reference https://github.com/libp2p/rust-libp2p/issues/2249 and https://github.com/libp2p/rust-libp2p/issues/2250
- Document blockers for https://github.com/libp2p/rust-libp2p/pull/2076

**Comment by mxinden** [comment]
**Changelog**

- With https://github.com/libp2p/rust-libp2p/pull/2248 merged, mark _Parallel connection attempts to increase hole punch success rate_ as done.

**Comment by mxinden** [comment]
**Changelog**
- https://github.com/libp2p/rust-libp2p/issues/2249 is fixed and released.
- Remaining work to enable basic hole punching in rust-libp2p
  - https://github.com/libp2p/rust-libp2p/pull/2066
  - https://github.com/libp2p/rust-libp2p/pull/2059/
  - https://github.com/libp2p/rust-libp2p/pull/2076

**Comment by mxinden** [comment]
Great news! I have been able to punch through both NATs and Firewalls using https://github.com/libp2p/rust-libp2p/pull/2066 https://github.com/libp2p/rust-libp2p/pull/2059/ and https://github.com/libp2p/rust-libp2p/pull/2076.

The "only" thing missing for basic hole punching in rust-libp2p are code-reviews for the pull requests above.

Do folks have some time to spare? I know it is a large amount of code. Reviews of subsets are just fine. Maybe @thomaseizinger, @elenaf9. @wngr, @divagant-martian or @MarcoPolo? :innocent: 

Also happy to post a write-up on how folks can punch some holes themselves in case there is interest.

**Comment by mxinden** [comment]
**Changelog**

- Track draft implementation for https://github.com/libp2p/rust-libp2p/issues/2250 namely https://github.com/libp2p/rust-libp2p/pull/2363
- Track https://github.com/libp2p/rust-libp2p/pull/2262/ instead of https://github.com/libp2p/rust-libp2p/pull/1672

**Comment by mxinden** [comment]
**Changelog**

* AutoNAT implementation merged via https://github.com/libp2p/rust-libp2p/pull/2262.
* Circuit Relay implementation merged via https://github.com/libp2p/rust-libp2p/pull/2059.

**Comment by mxinden** [comment]
**Changelog**
* https://github.com/libp2p/rust-libp2p/pull/2363 is merged and released.
* #2438 is merged.


Thus all protocols for basic hole punching are in `master` now :tada: If you want to punch holes yourself, check out https://github.com/libp2p/rust-libp2p/pull/2460.

**Comment by dariusc93** [comment]
The quic in the list should probably get updated with a newer pr, either the draft or the one that may get merged soon

**Comment by jxs** [comment]
Closing as everything has been addressed
