### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by mriise** [libp2p/rust-libp2p#2617]
This issue is an attempt to gather information relating to WASM support for rust-libp2p as well as serve as somewhat of a tracking / discussion issue.

## Transports

The general approach that we've been taking for transports it to use the `web-sys` bindings and code against those directly. This allows us to stay in Rust land without having to write any JS. Additionally, the acceptance criteria for any further transport is that they are integrated in the interop-test suite.

## Testing

We have additional tests that go beyond the interop suite in the `wasm-tests` directory: https://github.com/libp2p/rust-libp2p/tree/master/wasm-tests

---

```[tasklist]
- [x] https://github.com/libp2p/rust-libp2p/pull/4015
- [x] https://github.com/libp2p/rust-libp2p/pull/4248
- [ ] https://github.com/libp2p/rust-libp2p/issues/3611
- [ ] https://github.com/libp2p/rust-libp2p/issues/4389
- [ ] Remove `libp2p-wasm-ext` in the next breaking release
- [ ] https://github.com/libp2p/rust-libp2p/issues/4509
```

## Previous Implementations of WASM libp2p

- https://github.com/paritytech/smoldot
- https://github.com/iotaledger/identity.rs
- https://github.com/sireliah/wasm-p2p-experiment

**Comment by mriise** [comment]
Pinging people that have previously worked on WASM here (that I know of) @wngr @tomaka @expenses 

Also pinging @mxinden

Again, feel free to make suggestions or LMK if I missed anything that should be included!

**Comment by olanod** [comment]
A different kind of WASM support I'd like to bring to the table and something I'd like to experiment in the coming months(ideas and help will be welcomed) is the definition of a WASI interface that can be proposed later as `wasi-p2p` or something like that. Is a slightly different kind of WASM integration as the current direction is to be able to compile rust-libp2p to WASM expecting the host to provide calls that abstract the transport like using WebRTC with a set of custom host calls or perhaps the more standardized approach of targeting WASI that will have the sockets abstraction(could/will be polyfilled in the browser).

The proposal I mention is not so much for the browser support or environments that usually run a single bigger WASM blob where libp2p is included, my use case is embedded hardware where I want to allow a very constrained device to run a lightweight WASM interpreter like [WASM3](https://github.com/wasm3/wasm3) and run many  plugins that need to be as lightweight as possible, in systems where 1Mb is a lot and all there is I want to squeeze as many of those plugins as possible.  
This all means working on `no_std` support of rust-libp2p to run natively on the microcontroller using whatever is available in the chip like crypto acceleration and different connectivity stacks(LORA, bluetooth, wifi+smoltcp, etc.) and then exposing libp2p to the WASM plugin as an interface so they don't have to bundle it that can be used directly or via a version of libp2p that is just a shell that makes access to the lower level "syscalls" more convenient.

**Comment by thomaseizinger** [comment]
> A different kind of WASM support I'd like to bring to the table and something I'd like to experiment in the coming months(ideas and help will be welcomed) is the definition of a WASI interface that can be proposed later as `wasi-p2p` or something like that. Is a slightly different kind of WASM integration as the current direction is to be able to compile rust-libp2p to WASM expecting the host to provide calls that abstract the transport like using WebRTC with a set of custom host calls or perhaps the more standardized approach of targeting WASI that will have the sockets abstraction(could/will be polyfilled in the browser).
> 
> The proposal I mention is not so much for the browser support or environments that usually run a single bigger WASM blob where libp2p is included, my use case is embedded hardware where I want to allow a very constrained device to run a lightweight WASM interpreter like [WASM3](https://github.com/wasm3/wasm3) and run many plugins that need to be as lightweight as possible, in systems where 1Mb is a lot and all there is I want to squeeze as many of those plugins as possible. This all means working on `no_std` support of rust-libp2p to run natively on the microcontroller using whatever is available in the chip like crypto acceleration and different connectivity stacks(LORA, bluetooth, wifi+smoltcp, etc.) and then exposing libp2p to the WASM plugin as an interface so they don't have to bundle it that can be used directly or via a version of libp2p that is just a shell that makes access to the lower level "syscalls" more convenient.

These are some very interesting and exciting ideas! Here are some thoughts on it:

`rust-libp2p` already implements a kind of plugin architecture. `NetworkBehaviour`s are essentially plugins that can open / close new connections, open substreams etc. I am not sure if going for a `wasi-p2p` specification will be the most fruitful effort. What I could imagine to work much better is to try and get `libp2p-swarm` running on the micro controller natively with some static set of transports (bluetooth, tcp, etc) and have each of your plugins expose a component that corresponds to the `NetworkBehaviour` interface.

Another advantage of this approach is that with the `NetworkBehaviour` interface boundary, you are already getting a completely declarative interface around all the networking that is taking place. For example, you could easily log / intercept which component is establishing which network connections.

**Comment by vincev** [comment]
I have implemented a version of the chat example with libp2p WASM clients running in the browser connecting to a Floodsub server using a [Websocket transport](https://github.com/vincev/wasm-p2p-chat/blob/870b26d00122c633ead17700bc372e194917f66e/chat-client/src/main.rs#L195):

<img width="1081" alt="clients" src="https://user-images.githubusercontent.com/10183380/200174187-cdd6b493-2cad-4254-853b-d659e93aab1c.png">

I added the steps to build and run it in the [repo](https://github.com/vincev/wasm-p2p-chat). To make deployment easier I have implemented a Websocket [transport](https://github.com/vincev/libp2p-websys-transport) that uses [Websys](https://rustwasm.github.io/wasm-bindgen/web-sys/index.html) so that there is no need to package JS bindings and you can build a 100% rust client with a UI library like [egui](https://github.com/emilk/egui).

Keep in mind that I didn't do any serious testing, this is more of a proof of concept to test libp2p WASM support and get some feedback, I am happy to help and contribute any of this to libp2p if you think it may help.

**Comment by mxinden** [comment]
Wonderful work @vincev. Thanks for the elaborate `README.md`.

> Keep in mind that I didn't do any serious testing, this is more of a proof of concept to test libp2p WASM support and get some feedback, I am happy to help and contribute any of this to libp2p if you think it may help.

Yes. That would be great! Off the top of my head I am thinking of moving a version of https://github.com/vincev/wasm-p2p-chat into `misc/wasm-p2p-chat`. What do you think? @thomaseizinger any comments?

**Comment by vincev** [comment]
Thanks @mxinden I am glad you like it. 
 
> Yes. That would be great! Off the top of my head I am thinking of moving a version of https://github.com/vincev/wasm-p2p-chat into `misc/wasm-p2p-chat`. What do you think? @thomaseizinger any comments?

Sounds good to me, another option would be to have an examples folder for WASM browser apps that would include examples for Websocket and WebCRT but I guess that can be done later.

**Comment by thomaseizinger** [comment]
> Yes. That would be great! Off the top of my head I am thinking of moving a version of https://github.com/vincev/wasm-p2p-chat into `misc/wasm-p2p-chat`. What do you think? @thomaseizinger any comments?

Could be an opportunity to move towards https://github.com/libp2p/rust-libp2p/issues/3111.

**Comment by thomaseizinger** [comment]
@mriise Are you still interested in tracking these efforts? With https://github.com/libp2p/rust-libp2p/pull/4015, we now have a `web-sys`-based transport for WebTransport that is tested using the official interop-tests suite. We also have additional WASM-tests. Plus more and more protocol-crates now compile for WASM, see https://github.com/libp2p/rust-libp2p/pull/3973 for example.

More transports are being added, see https://github.com/libp2p/rust-libp2p/pull/4248 and https://github.com/libp2p/rust-libp2p/pull/4102.

I'd be curious what else we'd be missing. One thing I think would be really great is a full-stack `rust-libp2p` example where we have a server & a client, possibly reusing a common codebase and deploying them in the browser and as a server.

**Comment by DougAnderson444** [comment]
> be really great is a full-stack `rust-libp2p` example where we have a server & a client, possibly reusing a common codebase and deploying them in the browser and as a server.

💯 Full stack is definitely appealing! I'm looking forward to being able to use protocols like gossipsub isomorphically in the browser and server, not having to trouble shoot or be familiar with 2 different implementations (Rust and Javascript) -- a real bonus.

**Comment by thomaseizinger** [comment]
**Changelog:**

I've updated the PR description to reflect the current state and deleted several of the old points which I found not to be actionable.

**Comment by hahdsa** [comment]
No_std microcontrollers?

**Comment by elenaf9** [comment]
> No_std microcontrollers?

See https://github.com/libp2p/rust-libp2p/issues/627.
