### ISSUE TITLE
[Tracking Issue] transports/quic: Add QUIC Transport

### ISSUE THREAD

**Issue by elenaf9** [libp2p/rust-libp2p#2883]
# Summary

Implement the [QUIC](https://datatracker.ietf.org/doc/html/rfc9000) transport for rust-libp2p.

# Done criteria

- Quic can be used as a transport in the `Swarm` for communication between nodes that can directly reach each other
- TLS handshake is compliant with the [libp2p/specs TLS Handshake](https://github.com/libp2p/specs/blob/master/tls/tls.md) and unit tested
- Transport is unit & integration tested
- Benchmarked with [mxinden/libp2p-perf](https://github.com/mxinden/libp2p-perf)
- Tested again go-libp2p with Testground 
- Public API is documented

# Status Quo

Alpha implementation based on `quinn` crate. See https://github.com/libp2p/rust-libp2p/pull/3454.

<details><summary> Previous attempts / History </summary>

- #211
    - Initial Issue
- #563
    - First implementation using `picoquic`
    - Not using `quinn` because back then most `quinn` types were `!Send`
- #862
    - Continuation of #563
- #1334
    - Use `quinn-proto`
    - Continuation in branch [`tomaka/quiccc-again`](https://github.com/tomaka/libp2p-rs/tree/quiccc-again)
- #2144
    - Inspired by #1334 but does not share code
    - Related repo: https://github.com/ipfs-rust/libp2p-quic
    - published on crates.io as `libp2p-quic`
    - Support noise in addition to tls
    - Closed because quic+noise not in libp2p specs
- #2159
    - Continuation of #2144
    - Handles ecn codes and gso (throughput)
    - "Support for plugging in your own crypto"
- #2289 [**Most recent PR**] 
    - Initially a continuation of #2159
    - Later code was replaced with old code from `tomaka/quiccc-again` branch
- #2801 _Alternative to #2289_
   - Uses `quinn` instead of `quinn-proto` 
 
</details>

# Tasks

- [x] Finish kpp#23 (replaces elenaf9#6)
- [x] Finish remaining TODOs / FIXMEs in #2289:
- [x] Evaluate whether we should switch to use `UdpSocket` from `quinn_udp` instead of the rust `std` implementation
     - _Will stick with the rust `std` ones for the first version._
- [x] Review how backpressure is enforced throughout the whole implementation
  - If the application is too busy to read from an existing substream
  - If max inbound substreams is reached
  - If one connection is busy
- [x] Enhance docs
- [x] Enhance test
  - [x] Enhance ping test in [libp2p/test-plans](https://github.com/libp2p/test-plans) for interop tests with Testground
  - [x] More tests in general: backpressure, closing substreams, closing connections, limits, ..
- [x] Add QUIC support to mxinden/libp2p-perf for benchmarks (mxinden/libp2p-perf is replaced by https://github.com/libp2p/test-plans/blob/master/perf/)
- [x] libp2p/rust-libp2p#3133

**Long-term (not required for first implementation):**
- [x] Properly implement `Transport::dial_as_listener` to support hole-punching https://github.com/libp2p/rust-libp2p/pull/3964/
- Handle address change if a connection migrates
- [x] Handle / use ECN bits (Happening now with the move to quinn https://github.com/libp2p/rust-libp2p/pull/3454)
- [ ] Fix local_address when processing an incoming UDP datagram for a new connection on a socket that is bound to a wildcard address.
- [ ] Similarly, select correct socket when listening on wildcard address https://github.com/libp2p/rust-libp2p/issues/4259
- When first starting to listen, enable server-capabilities on existing client-only endpoint instead of creating a new one
- [x] Evaluate alternatives to the `quinn_proto` quic implementation
   - quinn https://github.com/libp2p/rust-libp2p/pull/3454
   - `s2n-quic` (AWS)
   - `quiche` (Cloudflare)
- Refactor tls-config handling to support `PeerId`-validation on TLS level: https://github.com/kpp/rust-libp2p/pull/27#discussion_r1018147667 https://github.com/libp2p/rust-libp2p/issues/2946

**Comment by mxinden** [comment]
Thanks for creating this @elenaf9!

Whenever you make a significant change to the original issue description, would you mind posting a comment like https://github.com/libp2p/rust-libp2p/issues/2052#issuecomment-827509552? That way, everyone subscribed to this issue gets a notification.

**Comment by elenaf9** [comment]
**Changelog**

  > Handle address change if a connection migrates
  
 -  Moved   to **Long-term**.  For now we can simply disable connection migration.

**Comment by elenaf9** [comment]
**Changelog**
`QuicMuxer` refactoring (elenaf9#6) was replaced and merged into #2289 with kpp#23:
- Updated the status-quo description
- Marked corresponding task as done.

**Comment by elenaf9** [comment]
**Changelog**

> Evaluate whether we should switch to use `UdpSocket` from `quinn_udp` instead of the rust `std` implementation 
- For the first implementation we will stick with `UdpSocket` from rust `std`. Integrating `quinn_udp::UdpSocket` requires additional complexity, and we don't strictly need it, especially if we plan on long-term switching to `quinn`.
> Handle / use ECN bits
- Moved to **Long-term** since the `UdpSocket` from `std` does not support this. 
> Fix local_address when processing an UDP datagram for a new incoming connection on a socket that is bound to a wildcard address
- Moved to **Long-term**. To fix this, we need to obtain the destination-ip of the first udp packet on the connection, which we can not access through the normal `UdpSocket` API. `quinn_udp` supports it for linux only. Long-term we can contribute support for other platforms as well (related issue: quinn-rs/quinn#508). For now the `local_address` will have an unspecified IP in this case.

**Comment by marten-seemann** [comment]
Should [Stateless Reset](https://datatracker.ietf.org/doc/html/rfc9000#section-10.3) handling / generation be added to the Long Term list?

**Comment by elenaf9** [comment]
**Changelog:**
- [x] Finish remaining TODOs / FIXMEs in Libp2p quic third attempt  #2289
- [x]  Enhance docs
- [x] Review how backpressure is enforced throughout the whole implementation 
       -> Described in the docs on [`endpoint::Driver`] in #2289

**Comment by thomaseizinger** [comment]
**Changelog:**

Added link to https://github.com/kpp/rust-libp2p/pull/27#discussion_r1018147667 so we don't forget to refactor the TLS-config handling.

**Comment by elenaf9** [comment]
**Changelog:**

- First QUIC implementation based on quinn proto is merged with #2289 :tada:. Updated Status Quo description.
- Add new task for support the `quic` codepoint / draft-29. #2289 only added support for `quic-v1`. See https://github.com/multiformats/multiaddr/issues/145.

**Comment by geotro** [comment]
I hope this is the right place to ask.

Is quic supported on relay-v2, and if not, what are the future plans regarding this?

**Comment by elenaf9** [comment]
@geotro yes it is supported. You can combine them in the same manner as it is done here with tcp and quic: 
https://github.com/libp2p/rust-libp2p/blob/a7148648858fe10e9ba4c2793c7e12392b49c0ab/transports/quic/tests/smoke.rs#L118-L136

and either replace the `tcp_transport` with your relay transport, or if you'd like to support tcp as well you have to combine (`OrTransport`) tcp and relay and then do the `upgrade`.

Does this help?

**Comment by elenaf9** [comment]
**Changelog**
- Add link to libp2p/rust-libp2p#3133

**Comment by geotro** [comment]
@elenaf9 it helps a bit, but I was hoping that once QUIC is implemented to be able to do UDP, as well as DCUTR.

Why are you referring to TCP in the context of QUIC?

I understand DCUTR with QUIC is not yet supported so I'll have to wait until that works before I retry it.

**Comment by elenaf9** [comment]
> Why are you referring to TCP in the context of QUIC?

I was referring to TCP to point out how you could support both TCP and QUIC together with the relay-v2 protocol. But TCP is not required, you may as well just combine QUIC and relay-v2.

**Comment by geotro** [comment]
Ah OK, thank you for clarifying this!

My use case requires DCUTR so I'm going to have to wait until this is available together with QUIC before I can begin testing/using it.  Very much looking forward to this as I hope it's going to greatly improve the success rates of establishing a direct connection!

**Comment by Frando** [comment]
Is there an issue or note somewhere what is missing for a working setup with QUIC + DCUTR + relay v2? Looking what pieces are missing there and would love any pointers.

**Comment by mxinden** [comment]
> Is there an issue or note somewhere what is missing for a working setup with QUIC + DCUTR + relay v2?

As far as I remember, the only thing missing is the implementation of `<quic::GenTransport as Transport>::dial_as_listener`.

https://github.com/libp2p/rust-libp2p/blob/56b3b8fe5a1e5d0b14ba7987a74ff3bc29f6b4e2/transports/quic/src/transport.rs#L182-L191

Note that https://github.com/libp2p/punchr/blob/main/rust-client/ is already using QUIC for hole punching, though only on the `Transport::dial` and not on the `Transport::dial_as_listener` side.

@Frando contributions here are welcome.

**Comment by mxinden** [comment]
Posting some in-progress research on the various Rust QUIC implementations out there.

### Verdict

Thus far my preference is still `quinn` via https://github.com/libp2p/rust-libp2p/pull/3454.
- We know at least `quinn-proto` works well for us (see `libp2p-quic` `alpha` release).
- It provides all the features we need (see table below).
- From what I can tell it has the most promising in-progress WebTransport implementation, see WebTransport column below.
- Thus far, unable to spot any performance issues via https://github.com/libp2p/test-plans/pull/163/, see https://observablehq.com/@mxinden-workspace/libp2p-perf using `quinn`.

With https://github.com/libp2p/rust-libp2p/pull/3454, `quinn` is no longer exposed on the public API surface. Thus we can easily switch out the underlying QUIC implementation in the future in case we ever want to move off of `quinn`.

Next step: Report our performance measurements to `quinn` maintainers to push https://github.com/quinn-rs/quinn/pull/1219 forward.

### Comparison


<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">integration effort</th>
<th scope="col" class="org-left">comments</th>
<th scope="col" class="org-left">WebTransport</th>
<th scope="col" class="org-left">Pacing</th>
<th scope="col" class="org-left">Managed UDP socket</th>
<th scope="col" class="org-left">GSO GRO</th>
<th scope="col" class="org-left">random bytes for hole-punching</th>
<th scope="col" class="org-left">TLS</th>
<th scope="col" class="org-left">license</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">quinn</td>
<td class="org-left">low, see <a href="https://github.com/libp2p/rust-libp2p/pull/3454">PR 3454</a></td>
<td class="org-left"><a href="https://github.com/quinn-rs/quinn/pull/1219">Uses unbounded channels</a></td>
<td class="org-left"><a href="https://github.com/quinn-rs/quinn/issues/1549">Work-in-progress</a></td>
<td class="org-left"><a href="https://github.com/quinn-rs/quinn/blob/main/quinn-proto/src/connection/pacing.rs">Pacing implementation</a></td>
<td class="org-left">Yes, through <code>quinn</code> crate</td>
<td class="org-left">Added with <a href="https://github.com/quinn-rs/quinn/pull/1024">GSO</a> <a href="https://github.com/quinn-rs/quinn/pull/1350">GRO</a></td>
<td class="org-left">Yes. One can gain access to the socket via <code>Endpoint::new</code></td>
<td class="org-left">rustls and ring</td>
<td class="org-left">Apache and MIT</td>
</tr>


<tr>
<td class="org-left">quiche</td>
<td class="org-left">unknown</td>
<td class="org-left">Large cooperation focused on performance (Cloudflare)</td>
<td class="org-left"><a href="https://github.com/cloudflare/quiche/issues/1114">Work-in-progress out of tree community owned</a></td>
<td class="org-left"><a href="https://github.com/cloudflare/quiche/pull/770">Pacing implementation</a></td>
<td class="org-left">No, see example <a href="https://github.com/cloudflare/quiche/blob/master/quiche/examples/server.rs">on manual management</a></td>
<td class="org-left">Doesn't manage socket, thus only <a href="https://github.com/cloudflare/quiche/pull/1138">example</a></td>
<td class="org-left">Yes, since UDP socket isn't managed</td>
<td class="org-left">boring ssl</td>
<td class="org-left"><a href="https://github.com/cloudflare/quiche/blob/master/COPYING">BSD 2-Clause</a></td>
</tr>


<tr>
<td class="org-left">s2n</td>
<td class="org-left">unknown</td>
<td class="org-left">Large cooperation focused on performance (AWS) \n use <a href="https://github.com/aws/s2n-quic/blob/main/quic/s2n-quic-transport/src/endpoint/handle.rs#L18-L21">unbounded channel to accept new connections</a>. Needs to be investigated whether that is a problem.</td>
<td class="org-left">Can't find any</td>
<td class="org-left">yes</td>
<td class="org-left">Yes, <a href="https://github.com/aws/s2n-quic/tree/main/quic/s2n-quic/src">see client and server</a></td>
<td class="org-left"><a href="https://github.com/aws/s2n-quic/pull/759">yes</a></td>
<td class="org-left">Not sure how to access the socket on a `Server`.</td>
<td class="org-left">s2n-tls</td>
<td class="org-left">Apache</td>
</tr>


<tr>
<td class="org-left">msquic</td>
<td class="org-left">unknown</td>
<td class="org-left">API for Rust, published on crates.io</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">neqo</td>
<td class="org-left">unknown</td>
<td class="org-left"><a href="https://github.com/mozilla/neqo/issues/1299">not published on crates.io</a></td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

//CC @marten-seemann

**Comment by marten-seemann** [comment]
Thanks for compiling this list @mxinden! This looks pretty comprehensive.

Some thoughts:
* Not sure if GSO and pacing warrant their own column, they’re just part of a long list of things a QUIC implementation can (optionally) do to speed things up. Others would be DPLPMTUD and ECN. They might serve as a proxy variable to see how advanced a QUIC stack is though.
* I expect WebTransport to be supported by more implementations once the draft makes more progress at the IETF. Not a lot of implementations are willing to pay the cost of shooting at a moving target, unless they have a very clear use case for the protocol (as quic-go obviously has, and Chrome’s implementation as well). This is even more so true after the adoption of the RELIABLE_RESET_STREAM draft at the last IETF meeting.
* Choosing Quinn (for now) doesn’t seem like a terrible choice, especially since the work is mostly driven by the community. Making the package API agnostic to the underlying QUIC implementation seems like a wise choice, enabling more experimentation in the future.

**Comment by kpp** [comment]
> Column `random bytes for hole-punching`
> quinn - Yes. One can gain access to the socket via Endpoint::new

The way it is implemented in https://github.com/libp2p/rust-libp2p/pull/3964 is through channels sending quinn_proto::Transmit. However the go impl uses multiple sockets with SO_REUSEPORT. So in quinn wrapper we can go both ways not sure which one is better.

**Comment by mxinden** [comment]
**Status Update**

https://github.com/libp2p/rust-libp2p/pull/3454 merged and thus our `libp2p-quic` implementation depends on upstream `quinn` directly. Thank you @kpp for the work. In case  no major blockers are discovered in `libp2p-quic` `v0.9.0-alpha` we can release it as `v0.9.0` soonish.

**Comment by thomaseizinger** [comment]
> **Status Update**
> 
> #3454 merged and thus our `libp2p-quic` implementation depends on upstream `quinn` directly. Thank you @kpp for the work. In case no major blockers are discovered in `libp2p-quic` `v0.9.0-alpha` we can release it as `v0.9.0` soonish.

It appears that the above description of this issue is rather outdated, do you mind updating it?

**Comment by mxinden** [comment]
**Status Update**

We just released [`libp2p` `v0.52.3`](https://github.com/libp2p/rust-libp2p/releases/tag/libp2p-v0.52.3) which contains a stable release of `libp2p-quic` `v0.9.2`. That is the first stable `libp2p-quic` release in rust-libp2p and thus a big step for the project :tada:

**Comment by mxinden** [comment]
I am closing here as the major milestone, adding QUIC to rust-libp2p, is achieved. Smaller follow-up improvements are tracked in individual issues.

Thank you to the many many many people involved in this effort. :heart:
