### ISSUE TITLE
Remove all deprecated items

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3647]
## Description

Remove all `#[deprecated]` items from the codebase.

Doing so is a breaking change, meaning we only want to do this once we cut the next breaking release.

## Motivation

Keeping things lean and lower complexity.

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by umgefahren** [comment]
I will take a go at this :)

**Comment by umgefahren** [comment]
I will take a go at this. I would suggest creating different PRs for each individual sub crate. This way we can merge the removal along with other breaking changes.

Although this is kind of boring work, I'm happy to be back :)

Tracking:
- [ ] `Identify` prefixed items #3698
- [ ] `Mdns` prefixed items #3699
- [ ] dcutr deprecated items #3700
- [ ] gossipsub deprecated items #3701
- [ ] relay
- [ ] `RequestResponse` deprecated items #3702

**Comment by Harshil-Jani** [comment]
Hey guys !! Any estimate about when the 0.52.0 version will be released ? We are eagerly waiting to see it coming since the project on which I am working has some dependency mismatch with matrix-sdk and the only way we can get through this normally is to wait till libp2p 0.52.0 is released.

**Comment by thomaseizinger** [comment]
> Hey guys !! Any estimate about when the 0.52.0 version will be released ? We are eagerly waiting to see it coming since the project on which I am working has some dependency mismatch with matrix-sdk and the only way we can get through this normally is to wait till libp2p 0.52.0 is released.

We are aiming to release within the next week, latest early June.

**Comment by mxinden** [comment]
@thomaseizinger, I assume that we don't need to hold the upcoming release for any remaining deprecation-removals. Please correct me if I'm wrong.

**Comment by thomaseizinger** [comment]
> @thomaseizinger, I assume that we don't need to hold the upcoming release for any remaining deprecation-removals. Please correct me if I'm wrong.

Nope, no need! I think apart from the `record` module in kademlia, all other deprecation warnings are actually unreleased.
