### ISSUE TITLE
Simplified handling of idle connections

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4306]
## Description

For a longer discussion see https://github.com/libp2p/rust-libp2p/discussions/3353#discussioncomment-6144804.

With https://github.com/libp2p/rust-libp2p/issues/3844, we are deprecating `KeepAlive::Until`. With https://github.com/libp2p/rust-libp2p/issues/4121, users can configure a `Swarm`-wide idle timeout that activates once all `ConnectionHandler`s report `KeepAlive::No`.

```[tasklist]
- [ ] https://github.com/libp2p/rust-libp2p/issues/3844
- [ ] https://github.com/libp2p/rust-libp2p/issues/4121
- [ ] https://github.com/libp2p/rust-libp2p/pull/4559
- [ ] https://github.com/libp2p/rust-libp2p/issues/4520
- [x] swarm: Make `ConnectionHandler::connection_keep_alive` optional and default to `KeepAlive::No`
- [x] Consider removing `KeepAlive` in favor of a boolean
```

## Motivation

Easier idle connection management for custom protocols. In particular, most users should not need to deal with idle connections and keep alive tracking but it should just work out of the box.

**Comment by thomaseizinger** [comment]
This is blocked by first landing:

- https://github.com/libp2p/rust-libp2p/issues/4121
- https://github.com/libp2p/rust-libp2p/issues/3844

I've tagged this as `difficulty:hard` because it touches many areas of the codebase. That said, the individual work items are fairly clear and isolated and can be tackled in steps.

**Comment by mxinden** [comment]
Thank you for the project management work here!

I am sure https://github.com/libp2p/rust-libp2p/issues/3844 is a good idea. Thus, as you list it above, I suggest landing it first.

https://github.com/libp2p/rust-libp2p/issues/4520 makes sense to me. I haven't put much thought into the concrete implementation that you suggest yet.

**Comment by thomaseizinger** [comment]
All done! :partying_face:
