### ISSUE TITLE
Hole punching (test setup & improvements)

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4523]
Preliminary tracking issue for tasks around the hole punching setup and improvements stemming from it.

```[tasklist]
- [ ] https://github.com/libp2p/rust-libp2p/issues/4496
- [ ] https://github.com/libp2p/rust-libp2p/issues/4519
- [ ] https://github.com/libp2p/rust-libp2p/issues/4504
```
