### ISSUE TITLE
AutoNAT v2

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4524]
Preliminary tracking issue around all the work that needs to happen around AutoNATv2 or issues that are associated with it.

```[tasklist]
### Implementation tasks
- [ ] https://github.com/libp2p/rust-libp2p/issues/4226
```
```[tasklist]
### Follow-up work
- [ ] https://github.com/libp2p/rust-libp2p/issues/3953
```
```[tasklist]
### Known bugs
- [ ] https://github.com/libp2p/rust-libp2p/issues/3986
- [ ] https://github.com/libp2p/rust-libp2p/issues/3889
- [ ] https://github.com/libp2p/rust-libp2p/issues/3308
- [ ] https://github.com/libp2p/rust-libp2p/issues/4873
- [ ] https://github.com/libp2p/rust-libp2p/issues/5059
```

**Comment by umgefahren** [comment]
Since this is my grant work, could you please assign me?

**Comment by mxinden** [comment]
For others to follow along, grant proposal: https://github.com/filecoin-project/devgrants/issues/1421
