### ISSUE TITLE
`v0.53` release

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#4545]
Tracking issue for the upcoming `v0.53` release to make sure we don't forget anything.

```[tasklist]
### PRs to include in final patch release
- [ ] https://github.com/libp2p/rust-libp2p/pull/4559
- [ ] https://github.com/libp2p/rust-libp2p/pull/4569
- [ ] https://github.com/libp2p/rust-libp2p/pull/4102
- [ ] https://github.com/libp2p/rust-libp2p/pull/4029
- [ ] https://github.com/libp2p/rust-libp2p/pull/4656
- [ ] https://github.com/libp2p/rust-libp2p/pull/4645
- [ ] https://github.com/libp2p/rust-libp2p/pull/4672
- [ ] https://github.com/libp2p/rust-libp2p/pull/4349
```

```[tasklist]
- [x] Mention transition to `tracing` in release notes on GitHub
- [x] Mention API improvements like `PollParameters` & `FromSwarm`
- [ ] https://github.com/libp2p/rust-libp2p/milestone/7
- [x] Remove all deprecated items
- [x] Mention more aggressive KeepAlive
- [ ] https://github.com/libp2p/rust-libp2p/pull/4581
```

**Comment by thomaseizinger** [comment]
https://github.com/libp2p/rust-libp2p/pull/4537#issuecomment-1732472371

**Comment by thomaseizinger** [comment]
This should be merged before releasing: https://github.com/libp2p/rust-libp2p/pull/4559

**Comment by thomaseizinger** [comment]
Changelog: I added https://github.com/libp2p/rust-libp2p/pull/4672 which attempts to fix a quite drastic bug in the new `SwarmBuilder`.

**Comment by thomaseizinger** [comment]
@mxinden @umgefahren What should we do about the API changes to `Transport` in regards to this release? I don't really want to block this release on all of AutoNATv2 being implemented but we also said to not merge the changes until we have validated the API.

Can we somehow get the best of both worlds and say with high certainty that the API designed in #4568 is what we need, merge that as part of `v0.53` and ship AutoNATv2 as a patch-release then?

**Comment by umgefahren** [comment]
We could, but we'd have to do all the necessary refactors over all transports.
However I suggested first testing if the Transport trait updates work with the AutoNATv2 implementation. I would leave the decision to @mxinden and @thomaseizinger

**Comment by thomaseizinger** [comment]
> However I suggested first testing if the Transport trait updates work with the AutoNATv2 implementation. I would leave the decision to @mxinden and @thomaseizinger

I am in favor of that too. It will mean that likely, AutoNATv2 will have to wait for the next breaking release though. There are a couple more PRs open that I'd like to merge but otherwise it is pretty much ready to go out.

The v0.52 release dragged on for about a month which I really want to avoid this time.

**Comment by umgefahren** [comment]
I'm fine with that, depending on when the next breaking release is scheduled.

**Comment by mxinden** [comment]
I suggest we don't block `v0.53` on AutoNATv2. I suggest we aim for AutoNATv2 and related changes in `v0.54`.

**Comment by dhuseby** [comment]
@thomaseizinger once this goes out should I update #4371 to ship as a non-breaking change? Or should we delay a day or two while I get it cleaned up to include in this release?

**Comment by thomaseizinger** [comment]
> @thomaseizinger once this goes out should I update #4371 to ship as a non-breaking change? Or should we delay a day or two while I get it cleaned up to include in this release?

Best to coordinate with @StemCll what their plans are on working on it.

I don't see any reason to block the release on it. I am writing the release notes today and then we should be good to go :)

**Comment by thomaseizinger** [comment]
I've drafted some release notes here: https://hackmd.io/@thomaseizinger/SkA-nMG7a/edit

Feedback is welcome, feel free to just edit it :)

@mxinden Once https://github.com/libp2p/rust-libp2p/pull/4794 is merged, feel free to cut a release with the above notes.

**Comment by mxinden** [comment]
> I've drafted some release notes here: https://hackmd.io/@thomaseizinger/SkA-nMG7a/edit

Very well written. Lots of attention to details. Made a couple of minor changes. Thank you @thomaseizinger. This will be an entertaining read for users.

> @mxinden Once #4794 is merged, feel free to cut a release with the above notes.

Will do :tada:

**Comment by thomaseizinger** [comment]
Couple of learnings from the making the release post (I'll send a docs PR later):

- Should not forget to check the "create discussion for release" button at the bottom of the page (see https://github.blog/changelog/2021-04-06-releases-support-comments-and-reactions-with-discussion-linking/).
- The markdown inside the release notes is not "commonmark", meaning single line breaks are actually rendered as line breaks and thus need to be removed for the text to flow nicely.
- We should directly tag people using `@` instead of writing markdown links as I did in the notes above.
