### ISSUE TITLE
Track: unreleased cargo dependencies

### ISSUE THREAD

**Issue by gnunicorn** [libp2p/rust-libp2p#593]
Tracking the dependencies that prevent us from releasing libp2p on crates.io (because we reference github sources and/or the code hasn't been published on crates.io yet).

Aside from all local crates, this includes:

- [x] chashmap v2.2.1 (https://github.com/redox-os/tfs#3e7dcdb0) in `datastore <- libp2p-peerstore <- libp2p-identify` 
- [x] aio-limited v0.1.0 (https://github.com/paritytech/aio-limited.git#1f42497d) in `libp2p-ratelimit`
- [x] eth-secp256k1 v0.5.7 (https://github.com/tomaka/rust-secp256k1?branch=pub-rand#30111804) in `libp2p-secio`
- [x] websocket v0.20.3 (https://github.com/tomaka/rust-websocket?branch=send#28ea5eb8) in`libp2p-websocket`
- [x] yamux v0.1.0 (https://github.com/paritytech/yamux#5c0d19af) in `libp2p-yamux`

----

Generated with the help of `cargo tree --all-targets --all-features`

**Comment by tomaka** [comment]
`chashmap` could probably be removed be removing `datastore` and `peerstore` entirely.
For secp: https://github.com/paritytech/rust-secp256k1/pull/14, however the version on crates.io doesn't correspond to ours either. This needs be sorted out better I think.
For websocket: https://github.com/websockets-rs/rust-websocket/pull/185#issuecomment-418703669
`aio-limited` and `yamux` probably just need to be published.

**Comment by vi** [comment]
Going to make (or try making) a `rust-websocket` release soon-ish.

Which unreleased changes do you depend on?

**Comment by dvdplm** [comment]
> For secp: [paritytech/rust-secp256k1#14](https://github.com/paritytech/rust-secp256k1/pull/14), however the version on crates.io doesn't correspond to ours either. This needs be sorted out better I think.

Do you know the reason we forked [the original](https://github.com/rust-bitcoin/rust-secp256k1/)? Is it possible to return to the mainline?

**Comment by twittner** [comment]
[Yamux](https://github.com/paritytech/yamux) has been published to [crates.io](https://crates.io/crates/yamux).
