### ISSUE TITLE
Tracking issue: roadmap to stabilization

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#596]
This issue should serve as a tracking issue for the roadmap to the first stable-ish version of rust-libp2p.
The core of the library has recently been rewritten and since then things have been a bit blurry, hence the need for an issue like this.

Things to do before a stable version of is possible:

- [ ] Agree on a `ProtocolsHandler` trait. (#573)
- [ ] Rewrite Kademlia to use `ProtocolsHandler` (#580)
- [ ] Rewrite Floodsub to use `ProtocolsHandler`.
- [ ] Rewrite Relay to use `ProtocolsHandler` (#585).
- [ ] Rewrite Ping to use `ProtocolsHandler` (#574)
- [ ] Rewrite Identify to use `ProtocolsHandler` (#579)
- [ ] Add a `NetworkBehaviour` trait.
- [ ] Thoroughly document the submodules of the `nodes` module.
- [ ] Add a `NetworkBehaviour` implementation of Kademlia.
- [ ] Add a `NetworkBehaviour` implementation of Floodsub.
- [ ] Add a `NetworkBehaviour` implementation of Relay.
- [ ] Add a `NetworkBehaviour` implementation of Ping.
- [ ] Add a `NetworkBehaviour` implementation of Identify.
- [ ] Add an easy way to combine multiple `NetworkBehaviour`s together, like a custom derive or a procedural macro.
- [ ] Add some easy ways to write your own `ProtocolsHandler` (not strictly necessary, but not very hard to do).
- [ ] Reorganize the modules within `core`.

Let me know if I forgot something.

**Comment by dvdplm** [comment]
>     * Reorganize the modules within `core`.

Can you perhaps add some more detail to this one?

**Comment by jamesray1** [comment]
> Add a NetworkBehaviour trait.

And add more detail for this one?

**Comment by tomaka** [comment]
> Can you perhaps add some more detail to this one?

I'm particularly thinking about the content of `nodes`. The name `nodes` doesn't really make sense, and the fact that they are part of a module while many types are visible only from the root of the crate doesn't make sense to me either.

**Comment by tomaka** [comment]
> And add more detail for this one? Although I guess it's fairly obvious.

Right now the `NodeHandler` (and `ProtocolsHandler`) emit and receive events for each individual node connected to us. However we also need code that acts over the network as a whole, for example performing Kademlia requests or handling floodsub in general.

Right now the user has do to that manually, which is both tedious and error prone. I think we need a system that makes it easy to plug functionalities together, and that would for example be a `NetworkBehaviour` trait.

**Comment by tomaka** [comment]
> Agree on a naming scheme for everything (eg. the Handler, Behaviour, etc. suffixes).

I think it's a good idea to have behaviours named after the protocol (eg. `KademliaBehaviour` -> `Kademlia`, `FloodsubBehaviour` -> `Floodsub`, etc.), while upgrades and handlers should be in submodules.

**Comment by jamesray1** [comment]
> Improve the identify network behaviour (#731).

I think this has the wrong PR?
